"urn:mace:dir:attribute-def:uid": "eppn"
"urn:oid:0.9.2342.19200300.100.1.1": "eppn"
"urn:mace:dir:attribute-def:mail": "mail"
"urn:oid:0.9.2342.19200300.100.1.3": "mail"
"urn:mace:dir:attribute-def:sn": "surname"
"urn:oid:2.5.4.4": "surname"
"urn:oid:2.5.4.42": "givenName"
"urn:mace:dir:attribute-def:givenName": "givenName"
"urn:oid:1.2.840.113556.1.2.102": "memberOf"
"urn:oid:1.2.840.113556.1.4.221": "sAMAccountName"
"urn:oid:1.3.6.1.4.1.5923.1.1.1.6": "eppn"
